# Generated by Django 2.2.4 on 2019-10-05 16:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('measurements', models.TextField()),
                ('neck', models.BinaryField()),
                ('sleeves', models.BinaryField()),
                ('waist', models.BinaryField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, default='default.jpg', upload_to='')),
                ('customer', models.ForeignKey(default=None, on_delete=None, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
